stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  image: node:10.15.1
  script:
    - npm install
    - npm test
    - npm run build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  only:
    - fe-gitlab-pages
  image: node:10.15.1
  script:
    - mv build public
  artifacts:
    paths:
      - public
